# Name: Makefile.windows
# Project: set-lcd-128x64
# Author: Rick Knowles
# Creation Date: 2011-10-11
# Tabsize: 4
# License: GNU GPL v2 (see License.txt)
# (modified from V-USB custom class example)

# You may use this file with
#   make -f Makefile.windows
# on Windows with MinGW instead of editing the main Makefile.

include Makefile

USBFLAGS = -I/usr/local/mingw/include
USBLIBS = -L/usr/local/mingw/lib -lusb
EXE_SUFFIX = .exe
